language: node.js
node_js:
  - 8

sudo: required
services:
  - docker

before_install:
  - docker build -t gilsway/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gilsway/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reack"
  env: "DockerReack-env"
  bucker_name: "elasticbeanstalk-us-east-2-521296517336"
  bucket_path: "docker-reack"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY